### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by dpursehouse**
Change-Id: I78fe9681f544b3852376deefa3e195edaed65a6a

### CODE REVIEW

**Comment by kbrebanov** [comment]
@dpursehouse I don't agree that these are _required_ dependencies for the role. By the default, it uses the **h2** database. So no requirement for PostgreSQL. Also, although gerrit is a code review tool for git, they both could be installed on different servers. Therefore, I would not want to force these dependencies to be installed.

**Comment by dpursehouse** [comment]
@kbrebanov I clarified the PostgreSQL dependency in 6433549.

git is declared as a dependency with no `when` clause, so as far as I understand it'll always be installed when running a playbook with the gerrit role.

**Comment by kbrebanov** [comment]
@dpursehouse Thanks for the update on the PostgreSQL dependency. As for the git dependency, will Gerrit install/run fine without git installed on the same machine? For example, if Gerrit can be installed on a separate machine than where the git repositories actually reside and simply point to it, then I would not want to force the dependency on git being installed.

**Comment by dpursehouse** [comment]
@kbrebanov the `bin/gerrit.sh` file uses `git config` to extract settings from the `etc/config.gerrit` file, for example:

```
get_config() {
  if test -f "$GERRIT_CONFIG" ; then
    if test "x$1" = x--int ; then
      # Git might not be able to expand "8g" properly.  If it gives
      # us 0 back retry for the raw string and expand ourselves.
      #
      n=`git config --file "$GERRIT_CONFIG" --int "$2"`
      if test x0 = "x$n" ; then
        n=`git config --file "$GERRIT_CONFIG" --get "$2"`
        case "$n" in
        *g) n=`expr ${n%%g} \* 1024`m ;;
        *k) n=`expr ${n%%k} \* 1024` ;;
        *)  : ;;
        esac
      fi
      echo "$n"
    else
      git config --file "$GERRIT_CONFIG" $1 "$2"
    fi
  fi
}
```

so I guess if `git` is not available, it won't work.

**Comment by dpursehouse** [comment]
@kbrebanov I have a question related to this.  If I want to run a playbook with the gerrit role to a server that already has git, java, and postgreSQL installed, is it possible to make it run without the dependencies?  In my local testing I have been simply commenting out the dependency lines.

**Comment by kbrebanov** [comment]
@dpursehouse Every task should have a tag that matches the role's name. Have you tried skipping tags when running your playbook?

```
ansible-playbook playbook.yml --skip-tags git,java,postgresql
```

**Comment by dpursehouse** [comment]
@kbrebanov Thanks for the suggestion.  I will try that when I find another test machine to deploy onto.  I found that deploying onto my main machine interferes with my development version of Gerrit :(

In the meantime is there anything else blocking this PR from being merged?

**Pull request merged**
